[package]
name = "aoc1a"
version = "0.1.0"
edition = "2021"

[dependencies]
png = "0.17.15"
#itertools = "0.13.0"

[[bin]]
name = "aoc-2"

[[bin]]
name = "aoc-3"

[[bin]]
name = "aoc-4"

[[bin]]
name = "aoc-5"

[[bin]]
name = "aoc-6"
